# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  Patch: '0'

steps:
- script: dotnet build --configuration $(buildConfiguration) --output "D:\a\1\a"
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'run MSTest'
  inputs:
    command: test
    projects: '**/tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'collect Code Coverage'
  inputs:
    command: test
    projects: '**/tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack $(buildConfiguration)'
  inputs:
    command: pack
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'

- task: NuGetAuthenticate@0
  displayName: 'authenticate NuGet'
  
- task: NuGetCommand@2
  displayName: 'push NuGet package'
  inputs:
    command: push
    publishVstsFeed: 'playground/pipelines-dotnet-core'
    allowPackageConflicts: true
